"""Curated recipe bank. Static content, not user data — hand-authored macro figures.

Each recipe is a dict with:
  id, name, slot (breakfast/lunch/dinner/snack), calories, protein_g, carbs_g, fat_g,
  prep_minutes, tags (list of dietary tags), ingredients (list of {name, qty, unit})
"""

VALID_SLOTS = {"breakfast", "lunch", "dinner", "snack"}
VALID_TAGS = {"vegetarian", "vegan", "gluten_free", "dairy_free", "high_protein", "quick"}


def _ing(name: str, qty: float, unit: str) -> dict:
    return {"name": name, "qty": qty, "unit": unit}


RECIPES = [
    # ---- Breakfast (14) ----
    {"id": "b01", "name": "Greek Yogurt & Berry Bowl", "slot": "breakfast",
     "calories": 320, "protein_g": 28, "carbs_g": 38, "fat_g": 7, "prep_minutes": 5,
     "tags": ["vegetarian", "high_protein", "quick"],
     "ingredients": [_ing("greek yogurt", 250, "g"), _ing("mixed berries", 120, "g"),
                     _ing("honey", 15, "ml"), _ing("granola", 30, "g")]},
    {"id": "b02", "name": "Veggie Egg Scramble", "slot": "breakfast",
     "calories": 380, "protein_g": 26, "carbs_g": 12, "fat_g": 25, "prep_minutes": 12,
     "tags": ["vegetarian", "gluten_free", "high_protein"],
     "ingredients": [_ing("eggs", 3, "unit"), _ing("bell pepper", 60, "g"),
                     _ing("spinach", 40, "g"), _ing("olive oil", 10, "ml"),
                     _ing("feta cheese", 30, "g")]},
    {"id": "b03", "name": "Overnight Oats with Peanut Butter", "slot": "breakfast",
     "calories": 410, "protein_g": 18, "carbs_g": 52, "fat_g": 15, "prep_minutes": 5,
     "tags": ["vegetarian", "quick"],
     "ingredients": [_ing("rolled oats", 70, "g"), _ing("milk", 200, "ml"),
                     _ing("peanut butter", 20, "g"), _ing("banana", 1, "unit")]},
    {"id": "b04", "name": "Smoked Salmon Bagel", "slot": "breakfast",
     "calories": 440, "protein_g": 27, "carbs_g": 45, "fat_g": 16, "prep_minutes": 8,
     "tags": ["high_protein", "quick"],
     "ingredients": [_ing("bagel", 1, "unit"), _ing("smoked salmon", 80, "g"),
                     _ing("cream cheese", 30, "g"), _ing("capers", 10, "g")]},
    {"id": "b05", "name": "Tofu Breakfast Scramble", "slot": "breakfast",
     "calories": 350, "protein_g": 24, "carbs_g": 20, "fat_g": 19, "prep_minutes": 15,
     "tags": ["vegan", "vegetarian", "dairy_free", "gluten_free", "high_protein"],
     "ingredients": [_ing("firm tofu", 200, "g"), _ing("turmeric", 2, "g"),
                     _ing("onion", 40, "g"), _ing("olive oil", 10, "ml"),
                     _ing("whole wheat toast", 2, "slice")]},
    {"id": "b06", "name": "Protein Pancakes", "slot": "breakfast",
     "calories": 420, "protein_g": 32, "carbs_g": 45, "fat_g": 11, "prep_minutes": 15,
     "tags": ["vegetarian", "high_protein"],
     "ingredients": [_ing("oat flour", 60, "g"), _ing("whey protein", 30, "g"),
                     _ing("eggs", 2, "unit"), _ing("milk", 100, "ml"),
                     _ing("maple syrup", 20, "ml")]},
    {"id": "b07", "name": "Avocado Toast with Egg", "slot": "breakfast",
     "calories": 390, "protein_g": 17, "carbs_g": 32, "fat_g": 22, "prep_minutes": 10,
     "tags": ["vegetarian", "quick"],
     "ingredients": [_ing("sourdough bread", 2, "slice"), _ing("avocado", 1, "unit"),
                     _ing("eggs", 1, "unit"), _ing("chili flakes", 1, "g")]},
    {"id": "b08", "name": "Cottage Cheese & Fruit", "slot": "breakfast",
     "calories": 300, "protein_g": 30, "carbs_g": 28, "fat_g": 7, "prep_minutes": 3,
     "tags": ["vegetarian", "gluten_free", "high_protein", "quick"],
     "ingredients": [_ing("cottage cheese", 250, "g"), _ing("pineapple", 100, "g"),
                     _ing("almonds", 15, "g")]},
    {"id": "b09", "name": "Steel-Cut Oatmeal with Walnuts", "slot": "breakfast",
     "calories": 360, "protein_g": 12, "carbs_g": 48, "fat_g": 14, "prep_minutes": 20,
     "tags": ["vegetarian", "vegan", "dairy_free", "gluten_free"],
     "ingredients": [_ing("steel-cut oats", 60, "g"), _ing("water", 250, "ml"),
                     _ing("walnuts", 20, "g"), _ing("cinnamon", 2, "g"),
                     _ing("maple syrup", 15, "ml")]},
    {"id": "b10", "name": "Breakfast Burrito", "slot": "breakfast",
     "calories": 480, "protein_g": 25, "carbs_g": 42, "fat_g": 24, "prep_minutes": 15,
     "tags": ["vegetarian", "high_protein"],
     "ingredients": [_ing("flour tortilla", 1, "unit"), _ing("eggs", 2, "unit"),
                     _ing("black beans", 80, "g"), _ing("cheddar cheese", 30, "g"),
                     _ing("salsa", 30, "g")]},
    {"id": "b11", "name": "Chia Seed Pudding", "slot": "breakfast",
     "calories": 310, "protein_g": 11, "carbs_g": 30, "fat_g": 17, "prep_minutes": 5,
     "tags": ["vegan", "vegetarian", "dairy_free", "gluten_free", "quick"],
     "ingredients": [_ing("chia seeds", 40, "g"), _ing("almond milk", 220, "ml"),
                     _ing("mixed berries", 80, "g"), _ing("maple syrup", 10, "ml")]},
    {"id": "b12", "name": "Breakfast Quinoa Bowl", "slot": "breakfast",
     "calories": 400, "protein_g": 15, "carbs_g": 55, "fat_g": 13, "prep_minutes": 18,
     "tags": ["vegetarian", "vegan", "dairy_free", "gluten_free"],
     "ingredients": [_ing("quinoa", 80, "g"), _ing("almond milk", 150, "ml"),
                     _ing("banana", 1, "unit"), _ing("almonds", 15, "g")]},
    {"id": "b13", "name": "Turkey Sausage & Sweet Potato Hash", "slot": "breakfast",
     "calories": 450, "protein_g": 28, "carbs_g": 35, "fat_g": 21, "prep_minutes": 20,
     "tags": ["gluten_free", "dairy_free", "high_protein"],
     "ingredients": [_ing("turkey sausage", 120, "g"), _ing("sweet potato", 150, "g"),
                     _ing("onion", 40, "g"), _ing("olive oil", 10, "ml")]},
    {"id": "b14", "name": "Protein Smoothie", "slot": "breakfast",
     "calories": 340, "protein_g": 30, "carbs_g": 40, "fat_g": 6, "prep_minutes": 5,
     "tags": ["vegetarian", "gluten_free", "high_protein", "quick"],
     "ingredients": [_ing("whey protein", 30, "g"), _ing("banana", 1, "unit"),
                     _ing("milk", 250, "ml"), _ing("frozen berries", 80, "g")]},

    # ---- Lunch (14) ----
    {"id": "l01", "name": "Grilled Chicken Caesar Salad", "slot": "lunch",
     "calories": 480, "protein_g": 40, "carbs_g": 18, "fat_g": 27, "prep_minutes": 15,
     "tags": ["gluten_free", "high_protein"],
     "ingredients": [_ing("chicken breast", 150, "g"), _ing("romaine lettuce", 100, "g"),
                     _ing("parmesan cheese", 20, "g"), _ing("caesar dressing", 30, "ml")]},
    {"id": "l02", "name": "Quinoa Chickpea Salad", "slot": "lunch",
     "calories": 420, "protein_g": 16, "carbs_g": 55, "fat_g": 16, "prep_minutes": 15,
     "tags": ["vegan", "vegetarian", "dairy_free", "gluten_free"],
     "ingredients": [_ing("quinoa", 80, "g"), _ing("chickpeas", 120, "g"),
                     _ing("cucumber", 60, "g"), _ing("olive oil", 15, "ml"),
                     _ing("lemon juice", 10, "ml")]},
    {"id": "l03", "name": "Turkey & Avocado Wrap", "slot": "lunch",
     "calories": 460, "protein_g": 32, "carbs_g": 38, "fat_g": 20, "prep_minutes": 10,
     "tags": ["high_protein", "quick"],
     "ingredients": [_ing("whole wheat tortilla", 1, "unit"), _ing("turkey breast", 120, "g"),
                     _ing("avocado", 0.5, "unit"), _ing("lettuce", 30, "g")]},
    {"id": "l04", "name": "Salmon Poke Bowl", "slot": "lunch",
     "calories": 520, "protein_g": 34, "carbs_g": 58, "fat_g": 17, "prep_minutes": 20,
     "tags": ["gluten_free", "dairy_free", "high_protein"],
     "ingredients": [_ing("salmon", 130, "g"), _ing("sushi rice", 150, "g"),
                     _ing("edamame", 60, "g"), _ing("soy sauce", 15, "ml"),
                     _ing("cucumber", 40, "g")]},
    {"id": "l05", "name": "Lentil Soup with Bread", "slot": "lunch",
     "calories": 400, "protein_g": 20, "carbs_g": 60, "fat_g": 9, "prep_minutes": 30,
     "tags": ["vegan", "vegetarian", "dairy_free"],
     "ingredients": [_ing("lentils", 100, "g"), _ing("carrot", 60, "g"),
                     _ing("onion", 40, "g"), _ing("whole grain bread", 1, "slice")]},
    {"id": "l06", "name": "Tuna Salad Sandwich", "slot": "lunch",
     "calories": 450, "protein_g": 33, "carbs_g": 40, "fat_g": 17, "prep_minutes": 10,
     "tags": ["high_protein", "quick"],
     "ingredients": [_ing("canned tuna", 150, "g"), _ing("whole wheat bread", 2, "slice"),
                     _ing("mayonnaise", 20, "g"), _ing("celery", 20, "g")]},
    {"id": "l07", "name": "Falafel Pita Plate", "slot": "lunch",
     "calories": 500, "protein_g": 18, "carbs_g": 62, "fat_g": 20, "prep_minutes": 20,
     "tags": ["vegetarian", "vegan", "dairy_free"],
     "ingredients": [_ing("falafel", 6, "unit"), _ing("pita bread", 1, "unit"),
                     _ing("hummus", 40, "g"), _ing("tomato", 50, "g")]},
    {"id": "l08", "name": "Beef & Broccoli Stir-Fry", "slot": "lunch",
     "calories": 540, "protein_g": 38, "carbs_g": 45, "fat_g": 22, "prep_minutes": 20,
     "tags": ["dairy_free", "high_protein"],
     "ingredients": [_ing("beef strips", 150, "g"), _ing("broccoli", 150, "g"),
                     _ing("jasmine rice", 120, "g"), _ing("soy sauce", 20, "ml")]},
    {"id": "l09", "name": "Caprese Sandwich", "slot": "lunch",
     "calories": 430, "protein_g": 18, "carbs_g": 40, "fat_g": 22, "prep_minutes": 8,
     "tags": ["vegetarian", "quick"],
     "ingredients": [_ing("ciabatta bread", 1, "unit"), _ing("mozzarella", 80, "g"),
                     _ing("tomato", 80, "g"), _ing("basil", 5, "g"),
                     _ing("balsamic glaze", 10, "ml")]},
    {"id": "l10", "name": "Shrimp Fried Rice", "slot": "lunch",
     "calories": 480, "protein_g": 30, "carbs_g": 55, "fat_g": 14, "prep_minutes": 18,
     "tags": ["dairy_free", "high_protein"],
     "ingredients": [_ing("shrimp", 150, "g"), _ing("jasmine rice", 150, "g"),
                     _ing("eggs", 1, "unit"), _ing("mixed vegetables", 100, "g"),
                     _ing("soy sauce", 15, "ml")]},
    {"id": "l11", "name": "Black Bean Burrito Bowl", "slot": "lunch",
     "calories": 510, "protein_g": 20, "carbs_g": 70, "fat_g": 15, "prep_minutes": 15,
     "tags": ["vegetarian", "vegan", "dairy_free", "gluten_free"],
     "ingredients": [_ing("black beans", 150, "g"), _ing("brown rice", 130, "g"),
                     _ing("corn", 60, "g"), _ing("avocado", 0.5, "unit"),
                     _ing("salsa", 30, "g")]},
    {"id": "l12", "name": "Greek Chicken Bowl", "slot": "lunch",
     "calories": 490, "protein_g": 38, "carbs_g": 40, "fat_g": 19, "prep_minutes": 20,
     "tags": ["gluten_free", "high_protein"],
     "ingredients": [_ing("chicken thigh", 150, "g"), _ing("brown rice", 100, "g"),
                     _ing("cucumber", 50, "g"), _ing("feta cheese", 30, "g"),
                     _ing("tzatziki", 30, "g")]},
    {"id": "l13", "name": "Veggie Sushi Rolls", "slot": "lunch",
     "calories": 380, "protein_g": 10, "carbs_g": 68, "fat_g": 6, "prep_minutes": 25,
     "tags": ["vegan", "vegetarian", "dairy_free"],
     "ingredients": [_ing("sushi rice", 180, "g"), _ing("nori sheets", 3, "unit"),
                     _ing("avocado", 0.5, "unit"), _ing("cucumber", 50, "g")]},
    {"id": "l14", "name": "Chicken Noodle Soup", "slot": "lunch",
     "calories": 360, "protein_g": 28, "carbs_g": 35, "fat_g": 10, "prep_minutes": 25,
     "tags": ["dairy_free", "high_protein"],
     "ingredients": [_ing("chicken breast", 120, "g"), _ing("egg noodles", 80, "g"),
                     _ing("carrot", 50, "g"), _ing("celery", 40, "g")]},

    # ---- Dinner (14) ----
    {"id": "d01", "name": "Baked Salmon with Asparagus", "slot": "dinner",
     "calories": 520, "protein_g": 40, "carbs_g": 15, "fat_g": 33, "prep_minutes": 25,
     "tags": ["gluten_free", "dairy_free", "high_protein"],
     "ingredients": [_ing("salmon fillet", 180, "g"), _ing("asparagus", 150, "g"),
                     _ing("olive oil", 15, "ml"), _ing("lemon", 0.5, "unit")]},
    {"id": "d02", "name": "Chicken Fajitas", "slot": "dinner",
     "calories": 550, "protein_g": 42, "carbs_g": 45, "fat_g": 21, "prep_minutes": 25,
     "tags": ["gluten_free", "dairy_free", "high_protein"],
     "ingredients": [_ing("chicken breast", 180, "g"), _ing("bell pepper", 100, "g"),
                     _ing("onion", 60, "g"), _ing("corn tortilla", 3, "unit")]},
    {"id": "d03", "name": "Spaghetti Bolognese", "slot": "dinner",
     "calories": 600, "protein_g": 32, "carbs_g": 70, "fat_g": 20, "prep_minutes": 35,
     "tags": [],
     "ingredients": [_ing("spaghetti", 100, "g"), _ing("ground beef", 150, "g"),
                     _ing("tomato sauce", 200, "g"), _ing("parmesan cheese", 20, "g")]},
    {"id": "d04", "name": "Tofu Vegetable Curry", "slot": "dinner",
     "calories": 480, "protein_g": 22, "carbs_g": 55, "fat_g": 18, "prep_minutes": 30,
     "tags": ["vegan", "vegetarian", "dairy_free", "gluten_free"],
     "ingredients": [_ing("firm tofu", 200, "g"), _ing("coconut milk", 150, "ml"),
                     _ing("mixed vegetables", 200, "g"), _ing("basmati rice", 100, "g"),
                     _ing("curry paste", 20, "g")]},
    {"id": "d05", "name": "Grilled Steak with Sweet Potato", "slot": "dinner",
     "calories": 620, "protein_g": 45, "carbs_g": 40, "fat_g": 30, "prep_minutes": 25,
     "tags": ["gluten_free", "dairy_free", "high_protein"],
     "ingredients": [_ing("sirloin steak", 200, "g"), _ing("sweet potato", 200, "g"),
                     _ing("green beans", 100, "g"), _ing("butter", 15, "g")]},
    {"id": "d06", "name": "Shrimp Zucchini Noodles", "slot": "dinner",
     "calories": 380, "protein_g": 34, "carbs_g": 18, "fat_g": 19, "prep_minutes": 20,
     "tags": ["gluten_free", "dairy_free", "high_protein", "quick"],
     "ingredients": [_ing("shrimp", 180, "g"), _ing("zucchini", 250, "g"),
                     _ing("garlic", 10, "g"), _ing("olive oil", 15, "ml")]},
    {"id": "d07", "name": "Baked Cod with Quinoa", "slot": "dinner",
     "calories": 460, "protein_g": 38, "carbs_g": 42, "fat_g": 14, "prep_minutes": 25,
     "tags": ["gluten_free", "dairy_free", "high_protein"],
     "ingredients": [_ing("cod fillet", 180, "g"), _ing("quinoa", 90, "g"),
                     _ing("cherry tomatoes", 80, "g"), _ing("olive oil", 10, "ml")]},
    {"id": "d08", "name": "Vegetable Lasagna", "slot": "dinner",
     "calories": 540, "protein_g": 24, "carbs_g": 55, "fat_g": 25, "prep_minutes": 45,
     "tags": ["vegetarian"],
     "ingredients": [_ing("lasagna noodles", 90, "g"), _ing("ricotta cheese", 100, "g"),
                     _ing("zucchini", 100, "g"), _ing("mozzarella", 60, "g"),
                     _ing("tomato sauce", 150, "g")]},
    {"id": "d09", "name": "Pork Tenderloin with Roasted Vegetables", "slot": "dinner",
     "calories": 500, "protein_g": 40, "carbs_g": 30, "fat_g": 24, "prep_minutes": 35,
     "tags": ["gluten_free", "dairy_free", "high_protein"],
     "ingredients": [_ing("pork tenderloin", 180, "g"), _ing("brussels sprouts", 150, "g"),
                     _ing("carrot", 100, "g"), _ing("olive oil", 15, "ml")]},
    {"id": "d10", "name": "Black Bean Enchiladas", "slot": "dinner",
     "calories": 520, "protein_g": 20, "carbs_g": 65, "fat_g": 20, "prep_minutes": 35,
     "tags": ["vegetarian"],
     "ingredients": [_ing("corn tortilla", 4, "unit"), _ing("black beans", 150, "g"),
                     _ing("cheddar cheese", 60, "g"), _ing("enchilada sauce", 120, "g")]},
    {"id": "d11", "name": "Turkey Meatballs with Zucchini Noodles", "slot": "dinner",
     "calories": 420, "protein_g": 38, "carbs_g": 20, "fat_g": 20, "prep_minutes": 30,
     "tags": ["gluten_free", "dairy_free", "high_protein"],
     "ingredients": [_ing("ground turkey", 180, "g"), _ing("zucchini", 200, "g"),
                     _ing("tomato sauce", 100, "g"), _ing("parmesan cheese", 15, "g")]},
    {"id": "d12", "name": "Miso Glazed Salmon with Rice", "slot": "dinner",
     "calories": 560, "protein_g": 38, "carbs_g": 50, "fat_g": 22, "prep_minutes": 25,
     "tags": ["dairy_free", "high_protein"],
     "ingredients": [_ing("salmon fillet", 180, "g"), _ing("white rice", 130, "g"),
                     _ing("miso paste", 20, "g"), _ing("bok choy", 100, "g")]},
    {"id": "d13", "name": "Vegetable Stir-Fry with Tofu", "slot": "dinner",
     "calories": 430, "protein_g": 22, "carbs_g": 50, "fat_g": 15, "prep_minutes": 20,
     "tags": ["vegan", "vegetarian", "dairy_free"],
     "ingredients": [_ing("firm tofu", 180, "g"), _ing("mixed vegetables", 200, "g"),
                     _ing("brown rice", 100, "g"), _ing("soy sauce", 15, "ml")]},
    {"id": "d14", "name": "Chicken Tikka Masala", "slot": "dinner",
     "calories": 580, "protein_g": 40, "carbs_g": 50, "fat_g": 24, "prep_minutes": 35,
     "tags": ["gluten_free", "high_protein"],
     "ingredients": [_ing("chicken breast", 180, "g"), _ing("tomato sauce", 150, "g"),
                     _ing("yogurt", 60, "g"), _ing("basmati rice", 120, "g")]},

    # ---- Snack (10) ----
    {"id": "s01", "name": "Apple with Almond Butter", "slot": "snack",
     "calories": 200, "protein_g": 5, "carbs_g": 25, "fat_g": 10, "prep_minutes": 2,
     "tags": ["vegan", "vegetarian", "dairy_free", "gluten_free", "quick"],
     "ingredients": [_ing("apple", 1, "unit"), _ing("almond butter", 20, "g")]},
    {"id": "s02", "name": "Protein Shake", "slot": "snack",
     "calories": 180, "protein_g": 25, "carbs_g": 8, "fat_g": 4, "prep_minutes": 2,
     "tags": ["vegetarian", "gluten_free", "high_protein", "quick"],
     "ingredients": [_ing("whey protein", 30, "g"), _ing("water", 300, "ml")]},
    {"id": "s03", "name": "Mixed Nuts", "slot": "snack",
     "calories": 220, "protein_g": 7, "carbs_g": 8, "fat_g": 19, "prep_minutes": 1,
     "tags": ["vegan", "vegetarian", "dairy_free", "gluten_free", "quick"],
     "ingredients": [_ing("mixed nuts", 35, "g")]},
    {"id": "s04", "name": "Hummus & Carrot Sticks", "slot": "snack",
     "calories": 170, "protein_g": 6, "carbs_g": 18, "fat_g": 9, "prep_minutes": 3,
     "tags": ["vegan", "vegetarian", "dairy_free", "gluten_free", "quick"],
     "ingredients": [_ing("hummus", 60, "g"), _ing("carrot", 100, "g")]},
    {"id": "s05", "name": "Hard-Boiled Eggs", "slot": "snack",
     "calories": 150, "protein_g": 13, "carbs_g": 1, "fat_g": 10, "prep_minutes": 10,
     "tags": ["vegetarian", "gluten_free", "dairy_free", "high_protein", "quick"],
     "ingredients": [_ing("eggs", 2, "unit")]},
    {"id": "s06", "name": "Cottage Cheese with Pineapple", "slot": "snack",
     "calories": 190, "protein_g": 18, "carbs_g": 20, "fat_g": 4, "prep_minutes": 2,
     "tags": ["vegetarian", "gluten_free", "high_protein", "quick"],
     "ingredients": [_ing("cottage cheese", 150, "g"), _ing("pineapple", 60, "g")]},
    {"id": "s07", "name": "Rice Cakes with Peanut Butter", "slot": "snack",
     "calories": 210, "protein_g": 7, "carbs_g": 24, "fat_g": 10, "prep_minutes": 2,
     "tags": ["vegan", "vegetarian", "dairy_free", "gluten_free", "quick"],
     "ingredients": [_ing("rice cakes", 2, "unit"), _ing("peanut butter", 20, "g")]},
    {"id": "s08", "name": "Greek Yogurt with Honey", "slot": "snack",
     "calories": 160, "protein_g": 15, "carbs_g": 18, "fat_g": 3, "prep_minutes": 2,
     "tags": ["vegetarian", "gluten_free", "high_protein", "quick"],
     "ingredients": [_ing("greek yogurt", 170, "g"), _ing("honey", 10, "ml")]},
    {"id": "s09", "name": "Trail Mix", "slot": "snack",
     "calories": 230, "protein_g": 6, "carbs_g": 22, "fat_g": 14, "prep_minutes": 1,
     "tags": ["vegan", "vegetarian", "dairy_free", "gluten_free", "quick"],
     "ingredients": [_ing("mixed nuts", 20, "g"), _ing("dried fruit", 20, "g"),
                     _ing("dark chocolate chips", 10, "g")]},
    {"id": "s10", "name": "Edamame", "slot": "snack",
     "calories": 140, "protein_g": 12, "carbs_g": 11, "fat_g": 5, "prep_minutes": 5,
     "tags": ["vegan", "vegetarian", "dairy_free", "gluten_free", "high_protein", "quick"],
     "ingredients": [_ing("edamame", 150, "g"), _ing("sea salt", 2, "g")]},
    {"id": "s11", "name": "Whole-Grain Crackers with Cheese", "slot": "snack",
     "calories": 210, "protein_g": 9, "carbs_g": 22, "fat_g": 10, "prep_minutes": 3,
     "tags": ["vegetarian", "quick"],
     "ingredients": [_ing("whole-grain crackers", 40, "g"), _ing("cheddar cheese", 30, "g")]},
    {"id": "s12", "name": "Granola Bar", "slot": "snack",
     "calories": 190, "protein_g": 5, "carbs_g": 29, "fat_g": 7, "prep_minutes": 1,
     "tags": ["vegetarian", "quick"],
     "ingredients": [_ing("granola bar", 1, "unit")]},
]


def get_recipe(recipe_id: str) -> dict:
    for recipe in RECIPES:
        if recipe["id"] == recipe_id:
            return recipe
    raise KeyError(f"No recipe with id {recipe_id!r}")


def recipes_for_slot(slot: str) -> list:
    return [r for r in RECIPES if r["slot"] == slot]
