const { test, expect } = require('@playwright/test');
const path = require('path');

const APP_URL = 'file://' + path.join(__dirname, '..', 'index.html');

test.describe('Security', () => {
  test('a malicious AI response is rendered as inert text, never executed', async ({ page }) => {
    await page.addInitScript(() => {
      window.fetch = async () => ({
        ok: true,
        json: async () => ({
          content: [
            {
              text: '</script><script>window.__xss_fired = true;</script>IMG_PAYLOAD<img src=x onerror="window.__xss_fired = true;">',
            },
          ],
        }),
      });
    });

    let dialogFired = false;
    page.on('dialog', async (d) => {
      dialogFired = true;
      await d.dismiss();
    });

    await page.goto(APP_URL);
    await page.click('[data-testid=preset-heteroscedastic]');
    await page.click('[data-testid=tab-diagnostics]');
    await page.fill('[data-testid=api-key-input]', 'sk-ant-fake-test-key');
    await page.click('[data-testid=explain-btn]');
    await expect(page.locator('[data-testid=ai-source]')).toContainText('Generated by Claude Haiku');

    const explanationText = await page.textContent('[data-testid=ai-explanation]');
    expect(explanationText).toContain('IMG_PAYLOAD');

    const xssFired = await page.evaluate(() => window.__xss_fired === true);
    expect(xssFired).toBe(false);
    expect(dialogFired).toBe(false);

    const scriptTagCount = await page.locator('script').count();
    // Only the 5 <script> tags this build itself authors should ever be present.
    expect(scriptTagCount).toBe(5);
  });

  test('the API key field is type="password" and the key is never written into the DOM elsewhere', async ({ page }) => {
    await page.goto(APP_URL);
    await page.click('[data-testid=tab-diagnostics]');
    const inputType = await page.getAttribute('[data-testid=api-key-input]', 'type');
    expect(inputType).toBe('password');
    await page.fill('[data-testid=api-key-input]', 'sk-ant-super-secret-value');
    const bodyHtml = await page.content();
    expect(bodyHtml).not.toContain('sk-ant-super-secret-value');
  });

  test('the app opens via file:// and makes zero network requests with no API key set', async ({ page }) => {
    const externalRequests = [];
    page.on('request', (req) => {
      if (!req.url().startsWith('file://')) externalRequests.push(req.url());
    });
    await page.goto(APP_URL);
    await page.click('[data-testid=tab-diagnostics]');
    await page.click('[data-testid=explain-btn]');
    await page.click('[data-testid=tab-multicollinearity]');
    await page.click('[data-testid=tab-quiz]');
    await page.click('[data-testid=start-quiz-btn]');
    await page.locator('#quiz-options .quiz-option-btn').first().click();
    expect(externalRequests).toEqual([]);
  });
});
