"""Self-contained HTML dashboard generator for ci-pulse."""

from __future__ import annotations

import html
import json
from datetime import datetime, timezone
from typing import Any

from analyzer import format_duration


_CHART_JS_CDN = "https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"


def _esc(s: str | None) -> str:
    return html.escape(str(s or ""), quote=True)


def _safe_json(obj: Any) -> str:
    """JSON-encode and unicode-escape < > to prevent script injection."""
    return json.dumps(obj).replace("<", "\\u003c").replace(">", "\\u003e")


def render_html(
    global_stats: dict[str, Any],
    workflow_stats: list[dict[str, Any]],
    weekly_trend: list[dict[str, Any]],
    ai_insights: str,
    generated_at: datetime | None = None,
) -> str:
    if generated_at is None:
        generated_at = datetime.now(timezone.utc)
    date_str = generated_at.strftime("%Y-%m-%d %H:%M UTC")

    total_runs = global_stats.get("total_runs", 0)
    total_failures = global_stats.get("total_failures", 0)
    total_ci_minutes = global_stats.get("total_ci_minutes", 0.0)
    repos_with_ci = global_stats.get("repos_with_ci", 0)
    failure_rate_pct = global_stats.get("overall_failure_rate", 0.0) * 100

    # Chart data: top 10 slowest workflows
    top_by_duration = sorted(workflow_stats, key=lambda s: s["avg_duration_s"], reverse=True)[:10]
    bar_labels = [f"{s['repo']}/{s['workflow_name']}" for s in top_by_duration]
    bar_data_avg = [round(s["avg_duration_s"], 1) for s in top_by_duration]
    bar_data_p95 = [round(s["p95_duration_s"], 1) for s in top_by_duration]

    # Chart data: failure rate by workflow (top 10 by failure count)
    top_by_failures = sorted(workflow_stats, key=lambda s: s["failure_count"], reverse=True)[:10]
    fail_labels = [f"{s['repo']}/{s['workflow_name']}" for s in top_by_failures]
    fail_data = [round(s["failure_rate"] * 100, 1) for s in top_by_failures]

    # Chart data: 30-day trend
    trend_labels = [w["week"] for w in weekly_trend]
    trend_avg = [w["avg_duration_s"] for w in weekly_trend]
    trend_failure = [round(w["failure_rate"] * 100, 1) for w in weekly_trend]

    # Table rows: all workflows sorted by avg_duration desc
    sorted_wf = sorted(workflow_stats, key=lambda s: s["avg_duration_s"], reverse=True)

    table_rows_html = ""
    for stat in sorted_wf:
        frate = stat["failure_rate"] * 100
        badge_cls = "badge-red" if frate > 20 else ("badge-amber" if frate > 5 else "badge-green")
        frate_badge = f'<span class="badge {badge_cls}">{frate:.0f}%</span>'
        avg_s = format_duration(stat["avg_duration_s"])
        p95_s = format_duration(stat["p95_duration_s"])
        table_rows_html += (
            f"<tr>"
            f"<td>{_esc(stat['repo'])}</td>"
            f"<td>{_esc(stat['workflow_name'])}</td>"
            f"<td data-sort='{stat['avg_duration_s']}'>{_esc(avg_s)}</td>"
            f"<td data-sort='{stat['p95_duration_s']}'>{_esc(p95_s)}</td>"
            f"<td>{frate_badge}</td>"
            f"<td>{stat['failure_count']}/{stat['total_runs']}</td>"
            f"</tr>\n"
        )

    ai_html = ""
    if ai_insights:
        escaped_insights = _esc(ai_insights)
        lines_html = "".join(
            f"<li>{_esc(line.lstrip('•- ').strip())}</li>"
            for line in ai_insights.splitlines()
            if line.strip().lstrip("•- ")
        )
        ai_html = f"""
    <section class="card ai-card">
      <h2>AI Insights</h2>
      <ul class="ai-bullets">{lines_html}</ul>
      <p class="ai-note">Generated by Claude Haiku from your CI metrics.</p>
    </section>"""
    else:
        ai_html = """
    <section class="card ai-card ai-empty">
      <h2>AI Insights</h2>
      <p>Set <code>ANTHROPIC_API_KEY</code> and re-run to get AI-powered bottleneck suggestions.</p>
    </section>"""

    empty_state = ""
    if not workflow_stats:
        empty_state = '<p class="empty">No completed workflow runs found in the selected time window. Try --days 90 or push a commit to trigger CI.</p>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ci-pulse — GitHub Actions Performance</title>
<script src="{_CHART_JS_CDN}"></script>
<style>
  :root {{
    --bg: #0d1117; --bg2: #161b22; --bg3: #21262d;
    --border: #30363d; --text: #e6edf3; --text2: #8b949e;
    --accent: #58a6ff; --green: #3fb950; --red: #f85149; --amber: #e3b341;
    --radius: 8px; --gap: 16px;
  }}
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text); font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 14px; line-height: 1.6; padding: var(--gap); }}
  h1 {{ font-size: 1.5rem; color: var(--text); margin-bottom: 4px; }}
  h2 {{ font-size: 1rem; color: var(--text2); text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 12px; }}
  .subtitle {{ color: var(--text2); font-size: 0.85rem; margin-bottom: 24px; }}
  .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: var(--gap); margin-bottom: var(--gap); }}
  .stat-card {{ background: var(--bg2); border: 1px solid var(--border); border-radius: var(--radius); padding: 16px; }}
  .stat-value {{ font-size: 2rem; font-weight: 700; color: var(--accent); line-height: 1; }}
  .stat-label {{ color: var(--text2); font-size: 0.8rem; margin-top: 4px; }}
  .cards-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(340px, 1fr)); gap: var(--gap); margin-bottom: var(--gap); }}
  .card {{ background: var(--bg2); border: 1px solid var(--border); border-radius: var(--radius); padding: 20px; }}
  .chart-wrap {{ position: relative; height: 260px; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid var(--border); font-size: 0.85rem; }}
  th {{ color: var(--text2); font-weight: 600; cursor: pointer; user-select: none; white-space: nowrap; }}
  th:hover {{ color: var(--text); }}
  tr:last-child td {{ border-bottom: none; }}
  tbody tr:hover {{ background: var(--bg3); }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 0.75rem; font-weight: 600; }}
  .badge-green {{ background: #1a3a2a; color: var(--green); }}
  .badge-amber {{ background: #3a2e1a; color: var(--amber); }}
  .badge-red {{ background: #3a1a1a; color: var(--red); }}
  .ai-bullets {{ list-style: none; padding: 0; }}
  .ai-bullets li {{ padding: 6px 0; border-bottom: 1px solid var(--border); color: var(--text); }}
  .ai-bullets li::before {{ content: "•"; color: var(--accent); margin-right: 8px; }}
  .ai-bullets li:last-child {{ border-bottom: none; }}
  .ai-note {{ color: var(--text2); font-size: 0.75rem; margin-top: 12px; }}
  .ai-empty p {{ color: var(--text2); }}
  .ai-empty code {{ color: var(--accent); background: var(--bg3); padding: 1px 4px; border-radius: 3px; }}
  .empty {{ color: var(--text2); text-align: center; padding: 40px 0; }}
  @media (max-width: 600px) {{ .cards-grid {{ grid-template-columns: 1fr; }} .chart-wrap {{ height: 200px; }} }}
</style>
</head>
<body>
<h1>ci-pulse</h1>
<p class="subtitle">GitHub Actions Performance Report &mdash; {_esc(date_str)}</p>

<div class="stats-grid">
  <div class="stat-card">
    <div class="stat-value">{total_runs}</div>
    <div class="stat-label">Total runs (30d)</div>
  </div>
  <div class="stat-card">
    <div class="stat-value" style="color:{'var(--red)' if failure_rate_pct > 15 else 'var(--amber)' if failure_rate_pct > 5 else 'var(--green)'}">{failure_rate_pct:.1f}%</div>
    <div class="stat-label">Failure rate</div>
  </div>
  <div class="stat-card">
    <div class="stat-value">{total_ci_minutes:.0f}</div>
    <div class="stat-label">CI minutes burned</div>
  </div>
  <div class="stat-card">
    <div class="stat-value">{repos_with_ci}</div>
    <div class="stat-label">Repos with CI</div>
  </div>
</div>

{empty_state}

<div class="cards-grid">
  <div class="card">
    <h2>Top Workflows by Duration</h2>
    <div class="chart-wrap"><canvas id="durationChart"></canvas></div>
  </div>
  <div class="card">
    <h2>Failure Rate by Workflow</h2>
    <div class="chart-wrap"><canvas id="failureChart"></canvas></div>
  </div>
</div>

<div class="card" style="margin-bottom: var(--gap);">
  <h2>30-Day Trend</h2>
  <div class="chart-wrap"><canvas id="trendChart"></canvas></div>
</div>

{ai_html}

<div class="card" style="margin-top: var(--gap); overflow-x: auto;">
  <h2>All Workflows</h2>
  <table id="wfTable">
    <thead>
      <tr>
        <th onclick="sortTable(0)">Repo ↕</th>
        <th onclick="sortTable(1)">Workflow ↕</th>
        <th onclick="sortTable(2)">Avg Duration ↕</th>
        <th onclick="sortTable(3)">p95 Duration ↕</th>
        <th onclick="sortTable(4)">Failure Rate ↕</th>
        <th onclick="sortTable(5)">Failures/Total ↕</th>
      </tr>
    </thead>
    <tbody>
{table_rows_html}
    </tbody>
  </table>
</div>

<script>
const durationCtx = document.getElementById('durationChart').getContext('2d');
new Chart(durationCtx, {{
  type: 'bar',
  data: {{
    labels: {_safe_json(bar_labels)},
    datasets: [
      {{ label: 'Avg (s)', data: {_safe_json(bar_data_avg)}, backgroundColor: 'rgba(88,166,255,0.7)', borderColor: 'rgba(88,166,255,1)', borderWidth: 1 }},
      {{ label: 'p95 (s)', data: {_safe_json(bar_data_p95)}, backgroundColor: 'rgba(227,179,65,0.5)', borderColor: 'rgba(227,179,65,1)', borderWidth: 1 }}
    ]
  }},
  options: {{
    responsive: true, maintainAspectRatio: false,
    indexAxis: 'y',
    plugins: {{ legend: {{ labels: {{ color: '#8b949e' }} }} }},
    scales: {{
      x: {{ ticks: {{ color: '#8b949e' }}, grid: {{ color: '#21262d' }} }},
      y: {{ ticks: {{ color: '#8b949e', font: {{ size: 10 }} }}, grid: {{ color: '#21262d' }} }}
    }}
  }}
}});

const failureCtx = document.getElementById('failureChart').getContext('2d');
new Chart(failureCtx, {{
  type: 'bar',
  data: {{
    labels: {_safe_json(fail_labels)},
    datasets: [{{ label: 'Failure %', data: {_safe_json(fail_data)}, backgroundColor: 'rgba(248,81,73,0.7)', borderColor: 'rgba(248,81,73,1)', borderWidth: 1 }}]
  }},
  options: {{
    responsive: true, maintainAspectRatio: false,
    indexAxis: 'y',
    plugins: {{ legend: {{ labels: {{ color: '#8b949e' }} }} }},
    scales: {{
      x: {{ min: 0, max: 100, ticks: {{ color: '#8b949e', callback: v => v + '%' }}, grid: {{ color: '#21262d' }} }},
      y: {{ ticks: {{ color: '#8b949e', font: {{ size: 10 }} }}, grid: {{ color: '#21262d' }} }}
    }}
  }}
}});

const trendCtx = document.getElementById('trendChart').getContext('2d');
new Chart(trendCtx, {{
  type: 'line',
  data: {{
    labels: {_safe_json(trend_labels)},
    datasets: [
      {{ label: 'Avg duration (s)', data: {_safe_json(trend_avg)}, borderColor: '#58a6ff', backgroundColor: 'rgba(88,166,255,0.1)', tension: 0.3, yAxisID: 'y' }},
      {{ label: 'Failure %', data: {_safe_json(trend_failure)}, borderColor: '#f85149', backgroundColor: 'rgba(248,81,73,0.1)', tension: 0.3, yAxisID: 'y1' }}
    ]
  }},
  options: {{
    responsive: true, maintainAspectRatio: false,
    plugins: {{ legend: {{ labels: {{ color: '#8b949e' }} }} }},
    scales: {{
      x: {{ ticks: {{ color: '#8b949e' }}, grid: {{ color: '#21262d' }} }},
      y: {{ ticks: {{ color: '#58a6ff' }}, grid: {{ color: '#21262d' }}, title: {{ display: true, text: 'Duration (s)', color: '#58a6ff' }} }},
      y1: {{ position: 'right', ticks: {{ color: '#f85149', callback: v => v + '%' }}, grid: {{ drawOnChartArea: false }}, title: {{ display: true, text: 'Failure %', color: '#f85149' }} }}
    }}
  }}
}});

let sortDir = {{}};
function sortTable(col) {{
  const tbody = document.querySelector('#wfTable tbody');
  const rows = Array.from(tbody.rows);
  sortDir[col] = !sortDir[col];
  rows.sort((a, b) => {{
    const av = a.cells[col].dataset.sort ?? a.cells[col].textContent.trim();
    const bv = b.cells[col].dataset.sort ?? b.cells[col].textContent.trim();
    const an = parseFloat(av), bn = parseFloat(bv);
    if (!isNaN(an) && !isNaN(bn)) return sortDir[col] ? an - bn : bn - an;
    return sortDir[col] ? av.localeCompare(bv) : bv.localeCompare(av);
  }});
  rows.forEach(r => tbody.appendChild(r));
}}
</script>
</body>
</html>"""
