"""Self-contained dark-mode HTML dashboard generator.

All paper/cluster text is external data (fetched from Semantic Scholar or
generated by an LLM) and is therefore treated as untrusted: it is delivered
to the page only as a JSON payload inside a <script type="application/json">
tag (with `</script` escaped so a hostile title can never close the tag
early), and every DOM node the page builds from that data is constructed
with `createElement`/`textContent`, never `innerHTML`.
"""
from __future__ import annotations

import json

CHART_JS_URL = "https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"


def _row_to_dict(row) -> dict:
    return {
        "paper_id": row["paper_id"],
        "title": row["title"],
        "year": row["year"],
        "venue": row["venue"],
        "citation_count": row["citation_count"],
        "external_url": row["external_url"],
    }


def build_payload(author_name: str, generated_at: str, clusters: list, papers: list, growth: list) -> dict:
    return {
        "author": author_name,
        "generated_at": generated_at,
        "clusters": [
            {
                "label": c["label"],
                "keywords": c["keywords"],
                "narrative": c["narrative"],
                "narrative_source": c["narrative_source"],
                "papers": [_row_to_dict(p) for p in c["papers"]],
            }
            for c in clusters
        ],
        "papers": [_row_to_dict(p) for p in papers],
        "growth": growth,
    }


def _escape_for_script_tag(json_text: str) -> str:
    return json_text.replace("</script", "<\\/script")


def render_dashboard(author_name: str, generated_at: str, clusters: list, papers: list, growth: list) -> str:
    payload = build_payload(author_name, generated_at, clusters, papers, growth)
    payload_json = _escape_for_script_tag(json.dumps(payload))

    return f"""<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Throughline</title>
<style>
  :root {{
    --bg: #0f1115; --panel: #171a21; --border: #2a2e38; --text: #e6e8ec;
    --muted: #9aa1ad; --accent: #6fb2ff; --good: #5ec98f; --bad: #ef6f6f;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; padding: 24px; background: var(--bg); color: var(--text);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  }}
  h1 {{ font-size: 1.4rem; margin: 0 0 4px; }}
  .sub {{ color: var(--muted); font-size: 0.85rem; margin-bottom: 20px; }}
  input[type="search"] {{
    width: 100%; max-width: 420px; padding: 8px 12px; margin-bottom: 20px;
    background: var(--panel); border: 1px solid var(--border); border-radius: 6px;
    color: var(--text); font-size: 0.95rem;
  }}
  .clusters {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 14px; margin-bottom: 28px; }}
  .card {{ background: var(--panel); border: 1px solid var(--border); border-radius: 8px; padding: 14px; }}
  .card h3 {{ margin: 0 0 6px; font-size: 1rem; color: var(--accent); }}
  .card .narrative {{ font-size: 0.88rem; line-height: 1.4; margin: 8px 0; }}
  .badge {{ display: inline-block; font-size: 0.7rem; padding: 2px 6px; border-radius: 4px; background: #24304a; color: var(--accent); }}
  .card ul {{ margin: 8px 0 0; padding-left: 18px; font-size: 0.82rem; color: var(--muted); }}
  table {{ width: 100%; border-collapse: collapse; background: var(--panel); border: 1px solid var(--border); border-radius: 8px; overflow: hidden; }}
  th, td {{ text-align: left; padding: 8px 10px; border-bottom: 1px solid var(--border); font-size: 0.85rem; }}
  th {{ cursor: pointer; color: var(--muted); user-select: none; }}
  tr:last-child td {{ border-bottom: none; }}
  .delta-pos {{ color: var(--good); }}
  .delta-neg {{ color: var(--bad); }}
  .section-title {{ font-size: 1.05rem; margin: 28px 0 10px; }}
  #chart-wrap {{ max-width: 900px; }}
  canvas {{ max-width: 100%; }}
  @media (max-width: 480px) {{
    body {{ padding: 14px; }}
    .clusters {{ grid-template-columns: 1fr; }}
  }}
</style>
</head>
<body>
<h1>Throughline</h1>
<div class="sub" id="header-sub"></div>
<input type="search" id="search-box" placeholder="Search papers by title or venue...">

<div class="section-title">Thematic Clusters</div>
<div class="clusters" id="clusters"></div>

<div class="section-title">Citation Growth</div>
<div id="chart-wrap"><canvas id="growth-chart" height="140"></canvas></div>
<table id="growth-fallback" hidden>
  <thead><tr><th>Paper</th><th>First</th><th>Latest</th><th>Delta</th></tr></thead>
  <tbody></tbody>
</table>

<div class="section-title">All Papers</div>
<table id="papers-table">
  <thead><tr>
    <th data-key="title">Title</th>
    <th data-key="year">Year</th>
    <th data-key="venue">Venue</th>
    <th data-key="citation_count">Citations</th>
  </tr></thead>
  <tbody id="papers-body"></tbody>
</table>

<script type="application/json" id="throughline-data">{payload_json}</script>
<script src="{CHART_JS_URL}"></script>
<script>
(function () {{
  var data = JSON.parse(document.getElementById('throughline-data').textContent);

  var sub = document.getElementById('header-sub');
  sub.textContent = data.author + ' \\u2014 ' + data.papers.length + ' papers \\u2014 generated ' + data.generated_at;

  function renderClusters(clusters) {{
    var container = document.getElementById('clusters');
    container.innerHTML = '';
    clusters.forEach(function (cluster) {{
      var card = document.createElement('div');
      card.className = 'card';

      var h3 = document.createElement('h3');
      h3.textContent = cluster.label;
      card.appendChild(h3);

      var badge = document.createElement('span');
      badge.className = 'badge';
      badge.textContent = cluster.narrative_source === 'ai' ? 'AI narrative' : 'deterministic summary';
      card.appendChild(badge);

      var narrative = document.createElement('p');
      narrative.className = 'narrative';
      narrative.textContent = cluster.narrative || '';
      card.appendChild(narrative);

      var ul = document.createElement('ul');
      cluster.papers.forEach(function (paper) {{
        var li = document.createElement('li');
        li.textContent = paper.title + (paper.year ? ' (' + paper.year + ')' : '');
        ul.appendChild(li);
      }});
      card.appendChild(ul);

      container.appendChild(card);
    }});
  }}

  function renderPapers(papers) {{
    var body = document.getElementById('papers-body');
    body.innerHTML = '';
    papers.forEach(function (paper) {{
      var tr = document.createElement('tr');
      ['title', 'year', 'venue', 'citation_count'].forEach(function (key) {{
        var td = document.createElement('td');
        var value = paper[key];
        td.textContent = (value === null || value === undefined) ? '\\u2014' : String(value);
        tr.appendChild(td);
      }});
      body.appendChild(tr);
    }});
  }}

  function renderGrowthFallback(growth) {{
    var table = document.getElementById('growth-fallback');
    var body = table.querySelector('tbody');
    body.innerHTML = '';
    growth.forEach(function (row) {{
      var tr = document.createElement('tr');
      [row.title, row.first_count, row.latest_count, row.delta].forEach(function (value, idx) {{
        var td = document.createElement('td');
        td.textContent = String(value);
        if (idx === 3) {{ td.className = row.delta >= 0 ? 'delta-pos' : 'delta-neg'; }}
        tr.appendChild(td);
      }});
      body.appendChild(tr);
    }});
    table.hidden = false;
  }}

  function renderGrowthChart(growth) {{
    var top = growth.slice(0, 12);
    if (typeof Chart === 'undefined') {{
      renderGrowthFallback(top);
      return;
    }}
    try {{
      var ctx = document.getElementById('growth-chart').getContext('2d');
      new Chart(ctx, {{
        type: 'bar',
        data: {{
          labels: top.map(function (r) {{ return r.title.length > 28 ? r.title.slice(0, 28) + '\\u2026' : r.title; }}),
          datasets: [{{ label: 'Citation growth', data: top.map(function (r) {{ return r.delta; }}), backgroundColor: '#6fb2ff' }}]
        }},
        options: {{ responsive: true, plugins: {{ legend: {{ display: false }} }} }}
      }});
    }} catch (err) {{
      renderGrowthFallback(top);
    }}
  }}

  renderClusters(data.clusters);
  renderPapers(data.papers);
  renderGrowthChart(data.growth);

  var sortState = {{ key: null, dir: 1 }};
  document.querySelectorAll('#papers-table th[data-key]').forEach(function (th) {{
    th.addEventListener('click', function () {{
      var key = th.getAttribute('data-key');
      sortState.dir = sortState.key === key ? -sortState.dir : 1;
      sortState.key = key;
      var sorted = data.papers.slice().sort(function (a, b) {{
        var av = a[key], bv = b[key];
        if (av === null || av === undefined) av = '';
        if (bv === null || bv === undefined) bv = '';
        if (av < bv) return -1 * sortState.dir;
        if (av > bv) return 1 * sortState.dir;
        return 0;
      }});
      renderPapers(sorted);
    }});
  }});

  document.getElementById('search-box').addEventListener('input', function (event) {{
    var query = event.target.value.trim().toLowerCase();
    if (!query) {{ renderPapers(data.papers); return; }}
    var filtered = data.papers.filter(function (paper) {{
      return (paper.title || '').toLowerCase().indexOf(query) !== -1 ||
             (paper.venue || '').toLowerCase().indexOf(query) !== -1;
    }});
    renderPapers(filtered);
  }});
}})();
</script>
</body>
</html>
"""
