// Heuristic Hunt — bias taxonomy and vignette data.
// Classic script (no ES modules) so the build opens directly via file://.
window.HH = window.HH || {};

HH.BIASES = [
  { id: 'anchoring', name: 'Anchoring Bias', definition: 'Relying too heavily on the first piece of information encountered (the "anchor") when making a decision, even when it is arbitrary or irrelevant.' },
  { id: 'confirmation', name: 'Confirmation Bias', definition: 'Favoring information that confirms existing beliefs while discounting, ignoring, or scrutinizing harder any contradictory evidence.' },
  { id: 'sunk_cost', name: 'Sunk Cost Fallacy', definition: 'Continuing a behavior or endeavor because of previously invested resources (time, money, effort) rather than weighing current costs and benefits.' },
  { id: 'availability', name: 'Availability Heuristic', definition: 'Judging how likely or common something is by how easily examples come to mind, rather than by its actual statistical frequency.' },
  { id: 'loss_aversion', name: 'Loss Aversion', definition: 'Weighing the pain of a loss more heavily than the pleasure of an equivalent gain, leading to choices driven by avoiding loss rather than maximizing expected value.' },
  { id: 'overconfidence', name: 'Overconfidence Bias', definition: 'Having excessive confidence in one’s own answers, abilities, or judgments relative to their actual accuracy.' },
  { id: 'hindsight', name: 'Hindsight Bias', definition: 'Perceiving past events as having been predictable after they have already occurred — the "I knew it all along" effect.' },
  { id: 'framing', name: 'Framing Effect', definition: 'Reacting differently to identical information depending on whether it is presented as a gain or a loss, a positive or a negative.' },
  { id: 'base_rate', name: 'Base Rate Neglect', definition: 'Ignoring general statistical base rates in favor of specific, vivid, or anecdotal information about a single case.' },
  { id: 'bandwagon', name: 'Bandwagon Effect', definition: 'Adopting a belief or behavior mainly because many other people are doing it, independent of the underlying evidence.' },
  { id: 'recency', name: 'Recency Bias', definition: 'Giving disproportionate weight to the most recent information or events when judging what will happen next.' },
  { id: 'survivorship', name: 'Survivorship Bias', definition: 'Drawing conclusions from a visible "surviving" subset of a group while overlooking the ones that did not survive and are absent from the data.' }
];

HH.VIGNETTES = [
  // Chapter 1 — obvious, textbook-clear
  { id: 1, chapter: 1, biasId: 'anchoring',
    text: 'A used car is listed at $28,000. After twenty minutes of negotiation, the buyer feels great about settling at $24,000 — even though comparable cars nearby are selling for $19,000.',
    distractors: ['framing', 'overconfidence', 'loss_aversion'],
    explanation: 'The listed $28,000 became the reference point ("anchor") the whole negotiation revolved around, making $24,000 feel like a win even though it is well above the real market price.' },
  { id: 2, chapter: 1, biasId: 'sunk_cost',
    text: 'You already paid $200 for a golf membership that includes ten free lessons. After the third lesson you realize you dislike golf, but you keep attending "because otherwise the money is wasted."',
    distractors: ['loss_aversion', 'anchoring', 'overconfidence'],
    explanation: 'The $200 is already spent and unrecoverable either way. Continuing lessons you dislike to "honor" that past spending, instead of judging the decision on future enjoyment alone, is the sunk cost fallacy.' },
  { id: 3, chapter: 1, biasId: 'confirmation',
    text: 'An investor believes a stock is undervalued. He reads five bullish analyst reports in a row but skips over three bearish ones sitting in the same inbox.',
    distractors: ['availability', 'overconfidence', 'bandwagon'],
    explanation: 'He is selectively engaging with evidence that supports what he already believes and ignoring contradicting evidence that is equally available — textbook confirmation bias.' },
  { id: 4, chapter: 1, biasId: 'availability',
    text: 'After seeing three news stories about shark attacks in one week, a swimmer becomes convinced ocean swimming is now unusually dangerous — even though shark attack rates have not changed this year.',
    distractors: ['recency', 'base_rate', 'hindsight'],
    explanation: 'Three vivid, easily recalled stories make the danger feel more common than it statistically is. That is the availability heuristic: ease of recall standing in for actual frequency.' },
  { id: 5, chapter: 1, biasId: 'loss_aversion',
    text: 'Offered a coin flip that pays $150 on heads and costs $100 on tails — a bet with positive expected value — most people in the study declined. The possible $100 loss felt worse than the possible $150 gain felt good.',
    distractors: ['framing', 'anchoring', 'overconfidence'],
    explanation: 'The bet is mathematically favorable, but people weigh potential losses more heavily than equivalent gains, so the fear of losing $100 outweighs the appeal of winning $150.' },
  { id: 6, chapter: 1, biasId: 'overconfidence',
    text: 'Ninety percent of drivers surveyed rated their own driving skill as "above average."',
    distractors: ['bandwagon', 'hindsight', 'confirmation'],
    explanation: 'By definition, only half of drivers can be above the median. Ninety percent rating themselves above average is a clean case of overestimating one’s own ability relative to reality.' },
  { id: 7, chapter: 1, biasId: 'hindsight',
    text: 'After a company’s stock crashed following a product recall, colleagues insisted "it was obvious this was coming" — despite no one having flagged the risk beforehand.',
    distractors: ['overconfidence', 'base_rate', 'recency'],
    explanation: 'Once the outcome is known, it retroactively feels like it was predictable all along, even though nobody actually predicted it in advance. That retroactive certainty is hindsight bias.' },
  { id: 8, chapter: 1, biasId: 'framing',
    text: 'A ground beef package labeled "90% lean" sold much better than an identical package labeled "10% fat," even though both describe exactly the same product.',
    distractors: ['anchoring', 'loss_aversion', 'confirmation'],
    explanation: 'The underlying fact is identical; only the presentation changed from positive ("lean") to negative ("fat"). Reacting differently to the same information based on its framing is the framing effect.' },
  { id: 9, chapter: 1, biasId: 'bandwagon',
    text: 'A new productivity app climbs the App Store charts, and downloads spike further simply because it is now listed as "trending." Many new users cite "everyone’s using it" as their main reason for trying it.',
    distractors: ['availability', 'confirmation', 'overconfidence'],
    explanation: 'People are adopting the app because of its popularity itself, not because of independent evidence it is good — the defining feature of the bandwagon effect.' },
  { id: 10, chapter: 1, biasId: 'recency',
    text: 'After three consecutive quarters of strong returns, an investor assumes a fund will keep outperforming and shifts more savings into it, discounting the fund’s much rockier ten-year track record.',
    distractors: ['availability', 'overconfidence', 'hindsight'],
    explanation: 'The most recent quarters are given far more weight than the longer, more representative history, which is recency bias driving the reallocation decision.' },

  // Chapter 2 — moderate subtlety
  { id: 11, chapter: 2, biasId: 'anchoring',
    text: 'During salary negotiations, a hiring manager asks the candidate’s current salary before naming a number. The final offer ends up unusually close to that figure, even though the market rate for the role is significantly higher.',
    distractors: ['framing', 'base_rate', 'loss_aversion'],
    explanation: 'The candidate’s old salary became the anchor the entire offer was built around, pulling the final number toward it and away from the role’s actual market rate.' },
  { id: 12, chapter: 2, biasId: 'confirmation',
    text: 'A lab director hypothesizes that sleep deprivation increases risk-taking. Reviewing pilot data, she spends extra time double-checking the handful of null-result subjects for coding errors, but accepts the supporting subjects’ data without a second look.',
    distractors: ['overconfidence', 'hindsight', 'base_rate'],
    explanation: 'She is applying a harsher evidentiary standard to data that contradicts her hypothesis than to data that supports it — confirmation bias operating through selective scrutiny rather than selective reading.' },
  { id: 13, chapter: 2, biasId: 'sunk_cost',
    text: 'A biotech firm has spent four years and $40M on a drug candidate. Interim trial data now looks weak, but leadership approves another $15M for a larger trial, reasoning that stopping now would "waste everything already spent."',
    distractors: ['loss_aversion', 'overconfidence', 'framing'],
    explanation: 'The $40M is gone regardless of what happens next. Approving more spending specifically to avoid "wasting" money that is already unrecoverable is the sunk cost fallacy at organizational scale.' },
  { id: 14, chapter: 2, biasId: 'availability',
    text: 'A grant reviewer rates "replication crisis" concerns as the single biggest threat facing the field, shortly after attending a conference where three separate talks happened to focus on failed replications.',
    distractors: ['recency', 'confirmation', 'base_rate'],
    explanation: 'A handful of vivid, recently-witnessed talks are shaping his sense of how big a threat replication failure is overall, rather than a broader look at the field’s actual replication statistics.' },
  { id: 15, chapter: 2, biasId: 'loss_aversion',
    text: 'A runner training for a marathon refuses to take a scheduled rest week, even though her coach and fatigue data both recommend it, because "skipping training days feels like losing fitness I already built."',
    distractors: ['sunk_cost', 'framing', 'overconfidence'],
    explanation: 'She is treating a forward-looking recovery decision as if it were about protecting past gains from being "lost," weighing the (illusory) loss of fitness more heavily than the real benefit of recovery.' },
  { id: 16, chapter: 2, biasId: 'overconfidence',
    text: 'A graduate student predicts a 90% chance of acceptance at a top journal on the first submission, despite the lab’s historical first-submission acceptance rate at that journal being under 15%.',
    distractors: ['base_rate', 'hindsight', 'confirmation'],
    explanation: 'The 90% figure vastly overstates the student’s actual odds relative to the lab’s own track record — a confident prediction that outruns the evidence supporting it.' },
  { id: 17, chapter: 2, biasId: 'framing',
    text: 'Two versions of a consent form describe the same procedure: one states it has a "95% survival rate," the other a "5% mortality rate." Far more participants agree to the procedure under the survival-rate wording.',
    distractors: ['loss_aversion', 'anchoring', 'confirmation'],
    explanation: '95% survival and 5% mortality describe the identical outcome. The difference in how many participants agree comes entirely from the positive versus negative framing of the same number.' },
  { id: 18, chapter: 2, biasId: 'base_rate',
    text: 'A screening test for a rare disorder is 98% accurate. A patient tests positive, and the clinician tells them they "almost certainly" have the disorder — without factoring in that the disorder affects only 1 in 10,000 people, which makes a false positive far more likely than a true one.',
    distractors: ['overconfidence', 'hindsight', 'availability'],
    explanation: 'Even a 98%-accurate test produces mostly false positives when the condition itself is extremely rare. Ignoring that rarity (the base rate) in favor of the test’s accuracy figure alone is base rate neglect.' },
  { id: 19, chapter: 2, biasId: 'bandwagon',
    text: 'In a lab meeting, three senior authors voice support for a particular statistical approach early in the discussion. Several junior members who privately had concerns about the method go along with it rather than raise objections.',
    distractors: ['confirmation', 'overconfidence', 'hindsight'],
    explanation: 'The junior members are adjusting their stated position to match the visible majority rather than acting on their own independent assessment — the bandwagon effect playing out socially in a meeting.' },
  { id: 20, chapter: 2, biasId: 'hindsight',
    text: 'After a startup fails, investors who backed it describe the warning signs as "blindingly obvious in retrospect" — the same signs that dozens of other still-operating startups also currently show.',
    distractors: ['survivorship', 'base_rate', 'overconfidence'],
    explanation: 'The signs only look "obviously" fatal now that the outcome is known. The same signs are present in companies that have not failed, which shows the "obviousness" is being reconstructed after the fact, not perceived in advance.' },

  // Chapter 3 — subtle, requires nuance
  { id: 21, chapter: 3, biasId: 'survivorship',
    text: 'A business magazine profiles five self-made millionaire founders who all say they "never gave up," concluding persistence is the key trait behind startup success — without interviewing any of the thousands of equally persistent founders whose companies failed.',
    distractors: ['hindsight', 'confirmation', 'bandwagon'],
    explanation: 'The sample only includes the "survivors." Countless equally persistent founders failed and are invisible in this data, so persistence cannot actually be isolated as the success factor from this evidence.' },
  { id: 22, chapter: 3, biasId: 'anchoring',
    text: 'A researcher pilot-tests a new anxiety scale and gets a mean score of 42 in a small sample. Months later, reviewing full-study data that clearly shows a different, lower population mean, she keeps flagging scores "unusually high" relative to that original pilot number.',
    distractors: ['recency', 'confirmation', 'base_rate'],
    explanation: 'The small pilot’s mean of 42 became her fixed reference point, distorting her judgment of the full study’s actual, better-powered distribution — an anchor she has not updated away from.' },
  { id: 23, chapter: 3, biasId: 'confirmation',
    text: 'A therapist who believes a client’s symptoms stem from childhood trauma asks detailed follow-up questions mainly when the client mentions childhood events, and moves the conversation along quickly when the client brings up recent workplace stress instead.',
    distractors: ['framing', 'availability', 'recency'],
    explanation: 'The therapist is steering inquiry toward evidence that fits the existing theory and giving less attention to a competing explanation, shaping what data even gets collected — confirmation bias affecting the interview itself.' },
  { id: 24, chapter: 3, biasId: 'loss_aversion',
    text: 'A department head keeps a chronically underperforming grant-funded project alive rather than reallocating the money to a more promising one, framing the shutdown internally as "losing the program" rather than as "freeing up resources for something better."',
    distractors: ['sunk_cost', 'framing', 'overconfidence'],
    explanation: 'The decision is being driven by how painful the loss of the program would feel, not by the money already spent (that is sunk_cost’s territory) or by comparing forward-looking costs and benefits.' },
  { id: 25, chapter: 3, biasId: 'overconfidence',
    text: 'A boat owner who has crossed a familiar lake hundreds of times in clear weather sets out despite a marginal small-craft advisory, reasoning that his experience with the lake makes the general warning not really apply to him.',
    distractors: ['base_rate', 'availability', 'anchoring'],
    explanation: 'His confidence in his own skill and familiarity leads him to discount a general safety warning that applies to conditions, not to any individual’s experience level — overconfidence overriding an external risk assessment.' },
  { id: 26, chapter: 3, biasId: 'framing',
    text: 'A retirement plan describes a fund’s fees as "only 1% annually." A second version of the same document describes the identical fee as "roughly 25% of your investment gains over 30 years." Employees shown the second version are far more likely to switch to a lower-fee fund.',
    distractors: ['loss_aversion', 'anchoring', 'base_rate'],
    explanation: 'Both descriptions refer to the exact same fee. Presenting it as a share of gains rather than an annual percentage changes behavior purely through framing, not through any change in the underlying facts.' },
  { id: 27, chapter: 3, biasId: 'recency',
    text: 'A portfolio manager overweights a sector after it posts strong gains in the past two months, revising a five-year allocation model built on decades of data, and later has to walk the change back after the sector reverts.',
    distractors: ['availability', 'overconfidence', 'hindsight'],
    explanation: 'Two months of strong performance is given more weight than the decades of data the original model was built on, which is recency bias distorting a longer-horizon decision.' },
  { id: 28, chapter: 3, biasId: 'bandwagon',
    text: 'A peer-review journal club consistently rates papers with well-known senior last authors as methodologically stronger than blinded versions of the same papers with the author names removed.',
    distractors: ['confirmation', 'overconfidence', 'anchoring'],
    explanation: 'The papers are identical; only the visible prestige of the author changes the group’s assessment. Deferring to the perceived consensus of "who is respected" rather than the actual methodology is the bandwagon effect.' },
  { id: 29, chapter: 3, biasId: 'base_rate',
    text: 'A hiring committee is impressed that a candidate "aced" a notoriously difficult technical interview that only 2% of applicants pass, and treats this as strong evidence the candidate is an elite performer — without weighing how many otherwise-average candidates also occasionally pass a noisy, low-pass-rate test purely by chance.',
    distractors: ['overconfidence', 'confirmation', 'hindsight'],
    explanation: 'A rare pass on a noisy test is vivid, but the committee neglects how often an average candidate would pass by chance alone given the test’s low, noisy pass rate — that is base rate neglect, not evidence of elite skill.' },
  { id: 30, chapter: 3, biasId: 'survivorship',
    text: 'A university highlights the 20% of psychology PhD graduates who landed tenure-track positions in its recruitment materials, describing the program as producing "highly employable academics," without mentioning outcomes for the other 80%.',
    distractors: ['base_rate', 'confirmation', 'bandwagon'],
    explanation: 'The recruitment material only shows the visible "successes." The 80% who did not land those positions are omitted from the data entirely, making the program look far more reliably successful than it is.' }
];
