"""Write bidirectional [[wiki-link]] backlinks into the user's own note files.

This is the one part of Connectome that edits files the user didn't ask it to
create (everything else is read-only). It is guarded accordingly: dry-run is
the default output, writing requires the notes directory to be a git working
tree (so an undo path always exists), and re-runs are idempotent via a single
delimited block per file rather than free-form insertion.
"""

from __future__ import annotations

import difflib
import hashlib
import os
import subprocess

import linking

BLOCK_START = "<!-- connectome:links:start -->"
BLOCK_END = "<!-- connectome:links:end -->"


def content_hash(body: str) -> str:
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def format_block(related: list[tuple[str, str, list[str]]]) -> str:
    """Build the delimited See Also block.

    related: (path, title, shared_concepts) tuples, already ranked highest
    score first. Link targets use the note's filename stem (Obsidian resolves
    [[links]] by filename), with the derived title as a display alias when it
    differs from the stem.
    """
    lines = [
        BLOCK_START,
        "**See also** _(generated by Connectome — edits inside this block are overwritten on the next `backlinks` run)_",
        "",
    ]
    for path, title, shared_concepts in related:
        stem = os.path.splitext(path)[0]
        target = f"[[{stem}|{title}]]" if title and title != stem else f"[[{stem}]]"
        concepts = ", ".join(shared_concepts[:5])
        suffix = f" — _shared: {concepts}_" if concepts else ""
        lines.append(f"- {target}{suffix}")
    lines.append(BLOCK_END)
    return "\n".join(lines)


def find_block(body: str) -> tuple[int, int] | None:
    """Return (start, end) char offsets of the delimited block, or None."""
    start = body.find(BLOCK_START)
    if start == -1:
        return None
    end = body.find(BLOCK_END, start)
    if end == -1:
        return None
    return start, end + len(BLOCK_END)


def apply_block(body: str, block: str | None) -> str:
    """Insert, replace, or remove the delimited block in body.

    block=None removes an existing block (e.g. a note whose last related note
    was deleted) and is a no-op if there was nothing to remove.
    """
    existing = find_block(body)

    if existing is None:
        if block is None:
            return body
        stripped = body.rstrip("\n")
        separator = "\n\n" if stripped else ""
        return f"{stripped}{separator}{block}\n"

    start, end = existing
    if block is not None:
        return body[:start] + block + body[end:]

    before = body[:start].rstrip("\n")
    after = body[end:].lstrip("\n")
    if before and after:
        return f"{before}\n\n{after}"
    return before or after


def plan_backlinks(
    notes: list, all_links: list, top_n: int = 5, lookup_notes: list | None = None
) -> list[dict]:
    """Compute the See Also block each note should have, without writing anything.

    notes: which notes to generate write-plans for — sqlite3.Row list from
    storage.all_notes(), typically scoped to one category since only files
    under a single --notes-dir get written to. lookup_notes: the universe
    used to resolve a related item's title/path for display in the See Also
    block; defaults to `notes` itself, but pass the full multi-category
    corpus here when `notes` is scoped, so a related item in another
    category (e.g. a paper related to a note) still resolves correctly
    instead of rendering as a broken [[|?]] link.
    all_links: from storage.get_all_links(). Returns one plan dict per note
    in `notes` with old/new body and whether it actually changed.
    """
    universe = lookup_notes if lookup_notes is not None else notes
    id_to_title = {note["id"]: note["title"] for note in universe}
    id_to_path = {note["id"]: note["path"] for note in universe}

    plans = []
    for note in notes:
        related = linking.related_to(note["id"], all_links, top_n=top_n)
        if related:
            block = format_block([
                (id_to_path.get(link.note_b, ""), id_to_title.get(link.note_b, "?"), link.shared_concepts)
                for link in related
            ])
        else:
            block = None
        new_body = apply_block(note["body"], block)
        plans.append({
            "path": note["path"],
            "title": note["title"],
            "old_body": note["body"],
            "new_body": new_body,
            "changed": new_body != note["body"],
        })
    return plans


def diff_text(path: str, old_body: str, new_body: str) -> str:
    diff = difflib.unified_diff(
        old_body.splitlines(keepends=True),
        new_body.splitlines(keepends=True),
        fromfile=f"a/{path}",
        tofile=f"b/{path}",
    )
    text = "".join(diff)
    return text if text else f"(no textual change to {path})\n"


def is_git_repo(path: str) -> bool:
    """True if path is inside a git working tree. Never raises."""
    if not os.path.isdir(path):
        return False
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--is-inside-work-tree"],
            cwd=path,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return result.returncode == 0 and result.stdout.strip() == "true"


def git_baseline_problem(path: str) -> str | None:
    """Check whether path has a real undo path: a git repo with at least one
    commit and a clean working tree, so our edits land as a clean, diffable,
    revertible change. Returns None if the baseline is fine, otherwise a
    human-readable reason writing should be refused.

    A bare `git init` alone is NOT sufficient — with no commit yet, `git diff`
    has nothing to compare our edits against.
    """
    if not is_git_repo(path):
        return f"'{path}' is not inside a git repository"

    try:
        head = subprocess.run(
            ["git", "rev-parse", "--verify", "HEAD"],
            cwd=path, capture_output=True, text=True, timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return f"could not check git history for '{path}'"
    if head.returncode != 0:
        return f"'{path}' is a git repo but has no commits yet — nothing for `git diff`/`git checkout` to fall back to"

    try:
        status = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=path, capture_output=True, text=True, timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return f"could not check git status for '{path}'"
    if status.returncode != 0:
        return f"could not check git status for '{path}'"
    if status.stdout.strip():
        return f"'{path}' has uncommitted changes already — commit or stash them first so our edits are a clean, separate diff"

    return None


def write_plans(notes_dir: str, changed_plans: list[dict]) -> tuple[list[str], list[str]]:
    """Write each plan's new_body to disk, refusing any note whose on-disk
    content no longer matches what was last indexed (an un-indexed edit could
    otherwise be silently overwritten). Returns (written_paths, stale_paths).
    """
    written, stale = [], []
    for plan in changed_plans:
        full_path = os.path.join(notes_dir, plan["path"])
        with open(full_path, "r", encoding="utf-8") as f:
            current = f.read()
        if content_hash(current) != content_hash(plan["old_body"]):
            stale.append(plan["path"])
            continue
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(plan["new_body"])
        written.append(plan["path"])
    return written, stale
