"""Deterministic timing, density, and objective-completeness checks.

Every number here is computed from the parsed lecture text — nothing is
guessed or generated by AI. The words-per-minute constant is a documented,
configurable assumption about instructional speaking pace, not a measurement.
"""
from __future__ import annotations

from dataclasses import dataclass, field

from parser import Lecture, Section

DEFAULT_WPM = 130.0
DEFAULT_TARGET_MINUTES = 50.0
BUDGET_TOLERANCE = 0.10
DENSITY_MULTIPLIER = 2.0
SPARSE_SECTIONS_PER_OBJECTIVE = 3


@dataclass
class SectionTiming:
    heading: str
    word_count: int
    estimated_minutes: float
    bullet_count: int


@dataclass
class LectureReport:
    total_minutes: float
    target_minutes: float
    budget_status: str  # "on_target" | "over_budget" | "under_budget"
    worst_section: str | None
    dense_sections: list[str] = field(default_factory=list)
    objective_flag: str = "ok"  # "ok" | "missing" | "sparse"
    section_timings: list[SectionTiming] = field(default_factory=list)
    heading_skip_warning: bool = False


def estimate_minutes(word_count: int, wpm: float = DEFAULT_WPM) -> float:
    if wpm <= 0:
        raise ValueError("wpm must be positive")
    return word_count / wpm


def classify_budget(
    total_minutes: float,
    target_minutes: float,
    tolerance: float = BUDGET_TOLERANCE,
) -> str:
    if target_minutes <= 0:
        raise ValueError("target_minutes must be positive")
    lower = target_minutes * (1 - tolerance)
    upper = target_minutes * (1 + tolerance)
    if total_minutes < lower:
        return "under_budget"
    if total_minutes > upper:
        return "over_budget"
    return "on_target"


def find_dense_sections(sections: list[Section]) -> list[str]:
    if len(sections) < 2:
        return []
    total_bullets = sum(s.bullet_count for s in sections)
    mean_bullets = total_bullets / len(sections)
    threshold = mean_bullets * DENSITY_MULTIPLIER
    if threshold <= 0:
        return []
    return [s.heading for s in sections if s.bullet_count > threshold]


def classify_objectives(objectives: list[str], sections: list[Section]) -> str:
    if len(objectives) == 0:
        return "missing"
    if len(objectives) * SPARSE_SECTIONS_PER_OBJECTIVE < len(sections):
        return "sparse"
    return "ok"


def build_report(
    lecture: Lecture,
    wpm: float = DEFAULT_WPM,
    target_minutes: float = DEFAULT_TARGET_MINUTES,
) -> LectureReport:
    section_timings = [
        SectionTiming(
            heading=s.heading,
            word_count=s.word_count,
            estimated_minutes=estimate_minutes(s.word_count, wpm),
            bullet_count=s.bullet_count,
        )
        for s in lecture.sections
    ]
    total_minutes = sum(st.estimated_minutes for st in section_timings)

    worst_section = None
    if section_timings:
        worst = max(section_timings, key=lambda st: st.estimated_minutes)
        if worst.estimated_minutes > 0:
            worst_section = worst.heading

    return LectureReport(
        total_minutes=total_minutes,
        target_minutes=target_minutes,
        budget_status=classify_budget(total_minutes, target_minutes),
        worst_section=worst_section,
        dense_sections=find_dense_sections(lecture.sections),
        objective_flag=classify_objectives(lecture.objectives, lecture.sections),
        section_timings=section_timings,
        heading_skip_warning=lecture.heading_skip_warning,
    )
