"""Deterministic discussion-question rule engine.

Each rule pairs a predicate over the extracted-facts dict with a question
template. A rule only contributes a question when its predicate matches a
fact the extraction layer actually found in the real abstract — nothing
here is generated by an AI model, and the rule engine's *input* facts come
from live PubMed data rather than a hand-authored taxonomy, which is the
deliberate point of difference from this repo's earlier taxonomy-driven
Category D generators.

Three generic questions are always appended so every case has at least 3
discussion questions even when extraction finds nothing distinctive in the
abstract.
"""
from typing import Callable, List, Tuple

from .extraction import Facts, indefinite_article

_Rule = Tuple[Callable[[Facts], bool], str]


def _is_small_sample(facts: Facts) -> bool:
    sample_size = facts.get("sample_size")
    return isinstance(sample_size, int) and sample_size < 30


def _is_correlational(facts: Facts) -> bool:
    return facts.get("methodology") == "correlational"


def _is_neuroimaging(facts: Facts) -> bool:
    return facts.get("methodology") in ("fMRI", "EEG")


def _lacks_control_language(facts: Facts) -> bool:
    return facts.get("has_control_comparison") is False


def _has_effect_size(facts: Facts) -> bool:
    return bool(facts.get("effect_size_text"))

def _is_meta_analysis(facts: Facts) -> bool:
    return facts.get("methodology") == "meta-analysis"


def _has_named_population(facts: Facts) -> bool:
    return bool(facts.get("population"))


_RULES: List[_Rule] = [
    (
        _is_small_sample,
        "This study reports a sample size of N={sample_size}. What are the "
        "implications for statistical power, and how confidently can these "
        "findings generalize beyond the sample studied?",
    ),
    (
        _is_correlational,
        "This is a correlational design. What are at least two plausible "
        "causal explanations for the reported association, and how would "
        "you design a study to distinguish between them?",
    ),
    (
        _is_neuroimaging,
        "This study uses {methodology}. Given how many statistical "
        "comparisons this type of analysis typically runs, what safeguard "
        "against false positives would you expect the authors to report?",
    ),
    (
        _lacks_control_language,
        "No explicit control or comparison condition is described in the "
        "abstract. What alternative explanations could account for the "
        "reported result in the absence of a comparison group?",
    ),
    (
        _has_effect_size,
        "The reported effect size is {effect_size_text}. Is this effect "
        "large enough to matter in a real-world setting, independent of "
        "whether it is statistically significant?",
    ),
    (
        _is_meta_analysis,
        "This is a meta-analysis or systematic review. What would need to "
        "be true of the underlying primary studies for this synthesis to "
        "be trustworthy, and how could publication bias threaten that?",
    ),
    (
        _has_named_population,
        "This study samples {population_article} {population}. How might "
        "the findings differ if the same study were run on a different "
        "population, and why?",
    ),
]

_FALLBACK_QUESTIONS = [
    "What is the single most important claim this study makes, and what "
    "evidence in the abstract directly supports it?",
    "If you were reviewing this paper for a journal, what is the first "
    "question you would ask the authors to clarify?",
    "How would you explain this study's main finding to someone outside "
    "the field in two sentences, without losing anything essential?",
]

_MAX_RULE_QUESTIONS = 5


def generate_discussion_questions(facts: Facts) -> List[str]:
    """Return a list of at least 3 (and at most 8) discussion questions
    for the given extracted-fact set. Deterministic: the same facts always
    produce the same questions in the same order."""
    format_facts = dict(facts)
    format_facts["population_article"] = indefinite_article(facts.get("population") or "")

    triggered: List[str] = []
    for predicate, template in _RULES:
        if len(triggered) >= _MAX_RULE_QUESTIONS:
            break
        if predicate(facts):
            try:
                triggered.append(template.format(**format_facts))
            except (KeyError, IndexError):
                continue
    return triggered + list(_FALLBACK_QUESTIONS)
