"""Panel Prep CLI — a mock NIH study-section critique for grant drafts.

Usage:
    python src/main.py submit <file> --project "R01 Empathy Renewal"
    python src/main.py list
    python src/main.py history "R01 Empathy Renewal"
    python src/main.py render "R01 Empathy Renewal" [--out report.html]

ANTHROPIC_API_KEY (optional): when set, each reviewer persona's critique is
generated by Claude Haiku instead of the deterministic fallback. Panel Prep
is fully functional with no key set.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src import checklist, db, parsing, render, reviewer

DEFAULT_DB_PATH = str(Path(__file__).resolve().parent.parent / "panel_prep.db")


def cmd_submit(args: argparse.Namespace, conn) -> None:
    path = Path(args.file)
    if not path.is_file():
        print(f"Error: no such file: {path}", file=sys.stderr)
        sys.exit(1)

    text = path.read_text(encoding="utf-8")
    sections = parsing.parse(text)
    if not sections:
        print("Error: the file appears to be empty — nothing to review.", file=sys.stderr)
        sys.exit(1)

    checklist_result = checklist.run(sections)
    review = reviewer.build_review(sections, checklist_result, api_key=args.api_key)
    result = db.insert_version(conn, args.project, sections, checklist_result, review, source_path=str(path))

    latest = db.get_latest(conn, args.project)
    print(f"Recorded {args.project!r} version {result['version_num']}.\n")
    print(render.render_terminal(args.project, latest))


def cmd_list(args: argparse.Namespace, conn) -> None:
    projects = db.list_projects(conn)
    if not projects:
        print("No projects yet. Run 'submit <file> --project NAME' to start one.")
        return
    for project in projects:
        latest = project["latest"]
        impact = latest["overall_impact"] if latest else "—"
        print(f"{project['name']:<40} versions={project['version_count']:<3} latest overall impact={impact}")


def cmd_history(args: argparse.Namespace, conn) -> None:
    try:
        history = db.get_history(conn, args.project)
    except db.ProjectNotFoundError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    if not history:
        print(f"No versions submitted yet for {args.project!r}.")
        return

    print(f"History for {args.project!r}:")
    for version in history:
        print(
            f"  v{version['version_num']} — {version['submitted_at']} — "
            f"overall impact {version['overall_impact']} — "
            f"checklist {version['checklist_pass_rate'] * 100:.0f}% — "
            f"{'AI-assisted' if version['ai_used'] else 'deterministic only'}"
        )


def cmd_render(args: argparse.Namespace, conn) -> None:
    try:
        history = db.get_history(conn, args.project)
    except db.ProjectNotFoundError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    if not history:
        print(f"Error: no versions submitted yet for {args.project!r}.", file=sys.stderr)
        sys.exit(1)

    html_output = render.render_html(args.project, history)
    out_path = Path(args.out)
    out_path.write_text(html_output, encoding="utf-8")
    print(f"HTML report written to {out_path}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Panel Prep — mock NIH study-section critique")
    parser.add_argument("--db", default=DEFAULT_DB_PATH, help="Path to the SQLite database file")
    subparsers = parser.add_subparsers(dest="command", required=True)

    p_submit = subparsers.add_parser("submit", help="Review a proposal draft file and record it as a new version")
    p_submit.add_argument("file", help="Path to a text/Markdown proposal draft")
    p_submit.add_argument("--project", required=True, help="Project name this version belongs to")
    p_submit.add_argument("--api-key", dest="api_key", default=None, help="Anthropic API key (else reads ANTHROPIC_API_KEY)")
    p_submit.set_defaults(func=cmd_submit)

    p_list = subparsers.add_parser("list", help="List all projects and their latest score")
    p_list.set_defaults(func=cmd_list)

    p_history = subparsers.add_parser("history", help="Show version-over-time score history for a project")
    p_history.add_argument("project")
    p_history.set_defaults(func=cmd_history)

    p_render = subparsers.add_parser("render", help="Render the self-contained HTML report for a project")
    p_render.add_argument("project")
    p_render.add_argument("--out", default="panel_prep_report.html")
    p_render.set_defaults(func=cmd_render)

    return parser


def main(argv: list[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    conn = db.connect(args.db)
    try:
        args.func(args, conn)
    finally:
        conn.close()


if __name__ == "__main__":
    main()
